from exception_handling import *
from built_in_function import *

if __name__ == "__main__":
    Try_Except_Final()